### ISSUE TITLE
Konfigurationsflow kunne ikke indlæses: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by perjmolsen** [MTrab/stromligning#28]
### Describe the issue

Jeg får denne fejl når jeg forsøger at konfigurere strømligning

Fejl
Konfigurationsflow kunne ikke indlæses: 500 Internal Server Error Server got itself in trouble

### What version of Home Assistant Core has the issue?

core-2024.11.0

### What was the last working version of Home Assistant Core?

core-2024.11.0

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Logger: aiohttp.server
Kilde: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
Første forekomst: 16.19.54 (6 forekomster)
Senest logget: 18.44.11

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1301, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1336, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stromligning/config_flow.py", line 99, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pystromligning/__init__.py", line 45, in set_location
    self.supplier = self._get_supplier()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pystromligning/__init__.py", line 60, in _get_supplier
    self._get_response(
  File "/usr/local/lib/python3.12/site-packages/pystromligning/__init__.py", line 120, in _get_response
    raise InvalidAPIResponse(
pystromligning.exceptions.InvalidAPIResponse: Error 404 received from the API
```

**Comment by perjmolsen** [comment]
![image](https://github.com/user-attachments/assets/6134f68a-5bd2-4762-9b87-a8d2b0fd71fa)

**Comment by MTrab** [comment]
404 is a server error.
Bot much I can do.

Try again later

**Comment by perjmolsen** [comment]
OK :) I'll try later

**Comment by boelle** [comment]
@perjmolsen 

hvad var din løsning? jeg får nemlig den samme ville høre hvor jeg evt kunne starte? det jo ikke nogen grund til at opfinde hjulet igen


Core
2026.4.2
Supervisor
2026.04.0
Operating System
17.2
Frontend
20260325.7


hvilken log kunne være interessant?

<img width="267" height="404" alt="Image" src="https://github.com/user-attachments/assets/107c1e9f-e35f-419e-984a-6d07b014dad7" />
<img width="267" height="404" alt="Image" src="https://github.com/user-attachments/assets/6cfe9685-73c2-4da6-9eaf-cadad7027da9" />

**Comment by MTrab** [comment]
Det er en integration - så det er core og så alt hvad der kunne vedrøre denne integration

**Comment by boelle** [comment]
<img width="1641" height="797" alt="Image" src="https://github.com/user-attachments/assets/80ffde8f-b720-4fb5-a3c2-10be63a6f4b3" />

så mega lang liste.... hvad kan jeg bruge som søge kriterie for at mindske det lidt til noget som du/i kan bruge?

**Comment by MTrab** [comment]
En god start ville jo nok være `stromligning` som er navnet på integrationen ;)

**Comment by boelle** [comment]
<img width="971" height="221" alt="Image" src="https://github.com/user-attachments/assets/853ec27d-083c-4ecf-9c72-828177dee9e0" />

det jo ikke meget, gætter på det er tæt på intetsigende?

og jo jeg har genstartet HA efter install.... :-D

[home-assistant_2026-04-15T15-06-08.591Z.log](https://github.com/user-attachments/files/26754170/home-assistant_2026-04-15T15-06-08.591Z.log)

**Comment by MTrab** [comment]
404 er en serverfejl - der er nok ikke andet at gøre end at vente

**Comment by boelle** [comment]
æv.... men jo tålmodighed

**Comment by MTrab** [comment]
Har du sat en home zone i din HA, eller står den bare til default (Amsterdam)?
Hvis ikke du har sat en home zone i Danmark, så kunne jeg faktisk godt forestille mig at APIet ville fejle

**Comment by boelle** [comment]
det har jeg i forbindelse med automationer der tænder og slukker lys i forhold til solen :-) men tjekker lige

**Comment by perjmolsen** [comment]
Hej Bo

Løsningen ved mig var at sætte adresse og land korrekt inde i Home assistant.
Du skal ind under Settings -> System-> Home information.

Mvh Per Olsen

**Comment by boelle** [comment]
<img width="1669" height="877" alt="Image" src="https://github.com/user-attachments/assets/56b9461e-6f50-40d0-a89a-162ca609eca3" />

@perjmolsen tjekker endnu engang men tror jeg har det på plads

EDIT: jo den er god nok, 

<img width="419" height="826" alt="Image" src="https://github.com/user-attachments/assets/c5183b47-73b8-4fd8-a317-07fdb6528aac" />

**Comment by boelle** [comment]
sur mølle men stadig 404/500

<img width="988" height="292" alt="Image" src="https://github.com/user-attachments/assets/4240df25-6a14-4073-84c1-f623c465a3bb" />

er det noget som sker tit ?

**Comment by MTrab** [comment]
Nej - men uanset - hvis det bliver ved, så lav lige et nyt issue med noget diagnostics, i stedet for at blive ved i et lukket issue ;)

I øvrigt kan jeg ikke se nogen issues med APIet lige nu - det ser ud til at svare fint når jeg forsøger
