### ISSUE TITLE
[BUG] iterable argument is empty / ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by mm98** [MTrab/stromligning#48]
### Describe the issue

The integration returns `iterable argument is empty` and/or `ZeroDivisionError` on the attributes (min, max and mean). No response back from nordpool maybe?

### What version of Home Assistant Core has the issue?

2024.12.1

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
2024-12-07 23:00:01.684 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_update when dispatching 'stromligning_signal_update': ()
Traceback (most recent call last):
  File "/config/custom_components/stromligning/sensor.py", line 399, in handle_update
    self._attr_native_value = self.entity_description.value_fn(
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._hass.data[DOMAIN][self._config.entry_id]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/stromligning/sensor.py", line 104, in <lambda>
    value_fn=lambda stromligning: stromligning.get_specific_today("min", vat=True),
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stromligning/api.py", line 186, in get_specific_today
    res = min(dataset, key=lambda k: k["price"]["value"])
ValueError: min() iterable argument is empty

2024-12-07 23:00:01.742 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_update when dispatching 'stromligning_signal_update': ()
Traceback (most recent call last):
  File "/config/custom_components/stromligning/sensor.py", line 399, in handle_update
    self._attr_native_value = self.entity_description.value_fn(
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._hass.data[DOMAIN][self._config.entry_id]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/stromligning/sensor.py", line 115, in <lambda>
    value_fn=lambda stromligning: stromligning.get_specific_today("min", vat=False),
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stromligning/api.py", line 186, in get_specific_today
    res = min(dataset, key=lambda k: k["price"]["value"])
ValueError: min() iterable argument is empty

2024-12-07 23:00:01.800 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_update when dispatching 'stromligning_signal_update': ()
Traceback (most recent call last):
  File "/config/custom_components/stromligning/sensor.py", line 399, in handle_update
    self._attr_native_value = self.entity_description.value_fn(
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._hass.data[DOMAIN][self._config.entry_id]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/stromligning/sensor.py", line 126, in <lambda>
    value_fn=lambda stromligning: stromligning.get_specific_today("max", vat=True),
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stromligning/api.py", line 188, in get_specific_today
    res = max(dataset, key=lambda k: k["price"]["value"])
ValueError: max() iterable argument is empty

2024-12-07 23:00:01.867 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_update when dispatching 'stromligning_signal_update': ()
Traceback (most recent call last):
  File "/config/custom_components/stromligning/sensor.py", line 399, in handle_update
    self._attr_native_value = self.entity_description.value_fn(
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._hass.data[DOMAIN][self._config.entry_id]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/stromligning/sensor.py", line 137, in <lambda>
    value_fn=lambda stromligning: stromligning.get_specific_today("max", vat=False),
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stromligning/api.py", line 188, in get_specific_today
    res = max(dataset, key=lambda k: k["price"]["value"])
ValueError: max() iterable argument is empty

2024-12-07 23:00:01.937 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_update when dispatching 'stromligning_signal_update': ()
Traceback (most recent call last):
  File "/config/custom_components/stromligning/sensor.py", line 399, in handle_update
    self._attr_native_value = self.entity_description.value_fn(
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._hass.data[DOMAIN][self._config.entry_id]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/stromligning/sensor.py", line 148, in <lambda>
    value_fn=lambda stromligning: stromligning.get_specific_today("mean", vat=True),
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stromligning/api.py", line 190, in get_specific_today
    return self.mean(dataset, vat)
           ~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/stromligning/api.py", line 171, in mean
    return val / num
           ~~~~^~~~~
ZeroDivisionError: division by zero

2024-12-07 23:00:01.996 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_update when dispatching 'stromligning_signal_update': ()
Traceback (most recent call last):
  File "/config/custom_components/stromligning/sensor.py", line 399, in handle_update
    self._attr_native_value = self.entity_description.value_fn(
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._hass.data[DOMAIN][self._config.entry_id]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/stromligning/sensor.py", line 159, in <lambda>
    value_fn=lambda stromligning: stromligning.get_specific_today(
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        "mean", vat=False
        ^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/stromligning/api.py", line 190, in get_specific_today
    return self.mean(dataset, vat)
           ~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/stromligning/api.py", line 171, in mean
    return val / num
           ~~~~^~~~~
ZeroDivisionError: division by zero
```

**Comment by mm98** [comment]
This is strangely a daily occurrence for me, but it only happens one time per day and then it is okay afterwards.

**Comment by MTrab** [comment]
Seems to happen around midnight here too

**Comment by mm98** [comment]
> Seems to happen around midnight here too

For me it is around 10-11am. Isn't really a problem - more just info, for when you make a change next time.

**Comment by mm98** [comment]
My bad, your actually right! I can see in the logs, that it happened around 11pm. I'll show myself out :)

**Comment by Boss-man** [comment]
Just to confirm that I also get the same error.

**Comment by Boss-man** [comment]
I now get the error every hour.
Did something change in the API or maybejust  because of the problems with Energi Data Service.

**Comment by mm98** [comment]
> Did something change in the API or maybejust because of the problems with Energi Data Service.

energidataservice.dk [reported](https://www.energidataservice.dk/news) they have problems currently.
![Image](https://github.com/user-attachments/assets/2d8e5030-79ea-484a-b28a-dab9a18ca552)

**Comment by Boss-man** [comment]
> energidataservice.dk [reported](https://www.energidataservice.dk/news) they have problems currently. Not much MTrab can do to fix this, since it is an external source / problem. ![Image](https://github.com/user-attachments/assets/2d8e5030-79ea-484a-b28a-dab9a18ca552)

But Strømligning should not use Energi Data Service, but the Strømligning API. 
And the "funny" thing is, I can reload the integration and then I get data for tomorrow, but until then I got this error every hour.

So something may go wrong if tomorrows data is late from Strømligning, and the integration is stuck or does not retry.

**Comment by tbowmo** [comment]
> But Strømligning should not use Energi Data Service, but the Strømligning API. And the "funny" thing is, I can reload the integration and then I get data for tomorrow, but until then I got this error every hour.

If I'm right, then strømligning API, and energi data service, get their data from the same "vendor" (nordpool), which apparently is the one having issues.
